#!/bin/bash

## Install site
cd $WEBROOT

fin exec "wp core install \
	--url=${VIRTUAL_HOST} \
	--title='My WordPress Site' \
	--admin_user=${WP_ADMIN_USER} \
	--admin_password=${WP_ADMIN_PASS} \
	--admin_email=${WP_ADMIN_EMAIL}"